-- ============================================================================
-- ROYRA JEWELS - PRODUCTION SECURE SUPABASE POSTGRESQL SCHEMA & MIGRATION
-- STRICT ROLE-BASED AUTHORIZATION & ROW LEVEL SECURITY (RLS)
-- IDEMPOTENT & SAFE TO RUN ON BOTH FRESH AND EXISTING/PARTIAL DATABASES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. BASE TABLE DEFINITIONS
-- ----------------------------------------------------------------------------

-- 1.1 PROFILES TABLE (Linked with Supabase auth.users)
-- Default role is strictly 'customer'. Only promoted users receive 'admin'.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  role TEXT DEFAULT 'customer' CHECK (role IN ('admin', 'staff', 'customer')),
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1.2 CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  image_url TEXT,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Draft', 'Archived')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1.3 PRODUCTS TABLE (BIGINT Identity Primary Key)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  sku TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL DEFAULT 'Uncategorized',
  product_type TEXT DEFAULT 'Solitaire',
  short_description TEXT,
  description TEXT,
  regular_price NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (regular_price >= 0),
  sale_price NUMERIC(10,2) CHECK (sale_price >= 0),
  price NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
  stock_quantity INTEGER DEFAULT 10 CHECK (stock_quantity >= 0),
  low_stock_alert INTEGER DEFAULT 3 CHECK (low_stock_alert >= 0),
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Draft', 'Out of Stock', 'Archived')),
  metal TEXT DEFAULT '18K Solid Gold / 925 Sterling Silver',
  purity TEXT,
  stone_name TEXT DEFAULT 'Certified Gemstone',
  stone_type TEXT,
  weight TEXT,
  finish TEXT DEFAULT '18K High Polish',
  collection TEXT DEFAULT 'everyday',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1.4 PRODUCT IMAGES TABLE (BIGINT product_id matches products.id identically)
CREATE TABLE IF NOT EXISTS public.product_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  storage_path TEXT,
  display_order INTEGER DEFAULT 0,
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2. DEFENSIVE MIGRATIONS FOR EXISTING / PARTIALLY-CREATED TABLES
-- (Guarantees every column exists before indexes, triggers, and policies run)
-- ----------------------------------------------------------------------------

-- 2.1 Profiles Columns Migration
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.profiles SET role = 'customer' WHERE role IS NULL;

-- 2.2 Categories Columns Migration
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active';
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.categories SET status = 'Active' WHERE status IS NULL;
UPDATE public.categories SET name = id WHERE name IS NULL;
UPDATE public.categories SET slug = LOWER(REGEXP_REPLACE(name, '[^a-zA-Z0-9]+', '-', 'g')) WHERE slug IS NULL;

-- 2.3 Products Columns Migration (Fixes missing 'category' and all other columns)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Uncategorized';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_type TEXT DEFAULT 'Solitaire';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS regular_price NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sale_price NUMERIC(10,2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS price NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 10;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS low_stock_alert INTEGER DEFAULT 3;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS metal TEXT DEFAULT '18K Solid Gold / 925 Sterling Silver';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS purity TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stone_name TEXT DEFAULT 'Certified Gemstone';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stone_type TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS weight TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS finish TEXT DEFAULT '18K High Polish';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS collection TEXT DEFAULT 'everyday';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Backfill default values on products for existing rows
UPDATE public.products SET category = 'Uncategorized' WHERE category IS NULL;
UPDATE public.products SET status = 'Active' WHERE status IS NULL;
UPDATE public.products SET price = COALESCE(regular_price, 0) WHERE price IS NULL;
UPDATE public.products SET regular_price = COALESCE(price, 0) WHERE regular_price IS NULL;
UPDATE public.products SET stock_quantity = 10 WHERE stock_quantity IS NULL;
UPDATE public.products SET low_stock_alert = 3 WHERE low_stock_alert IS NULL;
UPDATE public.products SET sku = CONCAT('ROY-', id) WHERE sku IS NULL;
UPDATE public.products SET slug = CONCAT('product-', id) WHERE slug IS NULL;

-- 2.4 Product Images Columns Migration & Type Safety
ALTER TABLE public.product_images ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE public.product_images ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.product_images ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE public.product_images ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
ALTER TABLE public.product_images ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT false;
ALTER TABLE public.product_images ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- Safely convert product_id column from TEXT to BIGINT if created in a previous run
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'product_images' AND column_name = 'product_id' AND data_type = 'text'
  ) THEN
    ALTER TABLE public.product_images ALTER COLUMN product_id TYPE BIGINT USING (product_id::bigint);
  END IF;
EXCEPTION
  WHEN OTHERS THEN NULL;
END $$;

-- ----------------------------------------------------------------------------
-- 3. PERFORMANCE INDEXES
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);
CREATE INDEX IF NOT EXISTS idx_categories_slug ON public.categories(slug);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

-- ----------------------------------------------------------------------------
-- 4. AUTOMATIC UPDATED_AT TRIGGER FUNCTION
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_categories_updated_at ON public.categories;
CREATE TRIGGER set_categories_updated_at
  BEFORE UPDATE ON public.categories
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ----------------------------------------------------------------------------
-- 5. REUSABLE ROLE-BASED ADMIN CHECK FUNCTION
-- Evaluates whether the currently authenticated caller has role = 'admin'
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public STABLE;

-- ----------------------------------------------------------------------------
-- 6. ENABLE ROW LEVEL SECURITY (RLS) ON ALL TABLES
-- ----------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 7. SAFE IDEMPOTENT RLS POLICIES FOR PROFILES
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can delete profiles" ON public.profiles;

CREATE POLICY "Users can read own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id OR public.is_admin())
  WITH CHECK (auth.uid() = id OR public.is_admin());

CREATE POLICY "Admins can delete profiles"
  ON public.profiles FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- ----------------------------------------------------------------------------
-- 8. SAFE IDEMPOTENT RLS POLICIES FOR CATEGORIES
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "Allow public read active categories" ON public.categories;
DROP POLICY IF EXISTS "Admin insert categories" ON public.categories;
DROP POLICY IF EXISTS "Admin update categories" ON public.categories;
DROP POLICY IF EXISTS "Admin delete categories" ON public.categories;

CREATE POLICY "Allow public read active categories"
  ON public.categories FOR SELECT
  USING (status = 'Active' OR public.is_admin());

CREATE POLICY "Admin insert categories"
  ON public.categories FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "Admin update categories"
  ON public.categories FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "Admin delete categories"
  ON public.categories FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- ----------------------------------------------------------------------------
-- 9. SAFE IDEMPOTENT RLS POLICIES FOR PRODUCTS
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "Allow public read active products" ON public.products;
DROP POLICY IF EXISTS "Admin insert products" ON public.products;
DROP POLICY IF EXISTS "Admin update products" ON public.products;
DROP POLICY IF EXISTS "Admin delete products" ON public.products;

CREATE POLICY "Allow public read active products"
  ON public.products FOR SELECT
  USING (status = 'Active' OR public.is_admin());

CREATE POLICY "Admin insert products"
  ON public.products FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "Admin update products"
  ON public.products FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "Admin delete products"
  ON public.products FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- ----------------------------------------------------------------------------
-- 10. SAFE IDEMPOTENT RLS POLICIES FOR PRODUCT_IMAGES
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "Allow public read active product images" ON public.product_images;
DROP POLICY IF EXISTS "Admin insert product images" ON public.product_images;
DROP POLICY IF EXISTS "Admin update product images" ON public.product_images;
DROP POLICY IF EXISTS "Admin delete product images" ON public.product_images;

CREATE POLICY "Allow public read active product images"
  ON public.product_images FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.products
      WHERE products.id = product_images.product_id
        AND products.status = 'Active'
    )
    OR public.is_admin()
  );

CREATE POLICY "Admin insert product images"
  ON public.product_images FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "Admin update product images"
  ON public.product_images FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "Admin delete product images"
  ON public.product_images FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- ----------------------------------------------------------------------------
-- 11. SUPABASE STORAGE BUCKET & ADMIN-ONLY STORAGE POLICIES
-- ----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public read storage product images" ON storage.objects;
DROP POLICY IF EXISTS "Admin upload storage product images" ON storage.objects;
DROP POLICY IF EXISTS "Admin update storage product images" ON storage.objects;
DROP POLICY IF EXISTS "Admin delete storage product images" ON storage.objects;

CREATE POLICY "Public read storage product images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'product-images');

CREATE POLICY "Admin upload storage product images"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'product-images' AND public.is_admin());

CREATE POLICY "Admin update storage product images"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'product-images' AND public.is_admin())
  WITH CHECK (bucket_id = 'product-images' AND public.is_admin());

CREATE POLICY "Admin delete storage product images"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'product-images' AND public.is_admin());

-- ----------------------------------------------------------------------------
-- 12. AUTOMATIC PROFILE CREATION TRIGGER ON AUTH SIGNUP
-- All new user signups are assigned role = 'customer' by default.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Royra Customer'),
    'customer'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 13. ADMIN PROMOTION COMMAND (RUN MANUALLY IN SUPABASE SQL EDITOR)
-- Replace 'YOUR_ADMIN_EMAIL' with your email to grant admin privileges:
-- ----------------------------------------------------------------------------
-- UPDATE public.profiles
-- SET role = 'admin', updated_at = NOW()
-- WHERE email = 'YOUR_ADMIN_EMAIL';

-- ============================================================================
-- 16. ROYRA CONTENT MANAGEMENT SYSTEM
-- MEDIA / BANNERS / COLLECTIONS / SETTINGS
-- Safe to run after the existing schema.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.media (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  file_name TEXT NOT NULL,
  storage_path TEXT NOT NULL UNIQUE,
  public_url TEXT NOT NULL,
  media_type TEXT DEFAULT 'general' CHECK (media_type IN ('general','banner','collection','product')),
  alt_text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.banners (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  internal_name TEXT,
  name TEXT,
  subtitle TEXT,
  description TEXT,
  desktop_image_url TEXT,
  mobile_image_url TEXT,
  button_text TEXT DEFAULT 'SHOP NOW →',
  button_link TEXT DEFAULT 'shop.html',
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'published', 'expired', 'archived', 'Active', 'Draft', 'Archived')),
  start_at TIMESTAMPTZ,
  end_at TIMESTAMPTZ,
  alt_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID
);

-- Migration-safe additions for existing public.banners table
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS internal_name TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS subtitle TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS desktop_image_url TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS mobile_image_url TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS button_text TEXT DEFAULT 'SHOP NOW →';
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS button_link TEXT DEFAULT 'shop.html';
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS start_at TIMESTAMPTZ;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS end_at TIMESTAMPTZ;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS alt_text TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS created_by UUID;

CREATE TABLE IF NOT EXISTS public.collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  short_description TEXT,
  collection_image_url TEXT,
  banner_image_url TEXT,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active','Draft','Archived')),
  display_order INTEGER DEFAULT 1,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.collection_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES public.collections(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  display_order INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (collection_id, product_id)
);

-- site_settings already exists in the current ROYRA JEWELS project with explicit CMS fields.
-- Keep that structure and extend it safely for the commerce/admin settings UI.
CREATE TABLE IF NOT EXISTS public.site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name TEXT,
  logo_url TEXT,
  hero_badge TEXT,
  hero_title TEXT,
  hero_description TEXT,
  hero_image_url TEXT,
  primary_button_text TEXT,
  primary_button_link TEXT,
  secondary_button_text TEXT,
  secondary_button_link TEXT,
  announcement_text TEXT,
  announcement_subtext TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  whatsapp_number TEXT,
  instagram_url TEXT,
  facebook_url TEXT,
  footer_copyright TEXT,
  currency TEXT DEFAULT 'INR',
  tax_rate NUMERIC(10,2) DEFAULT 0,
  shipping_fee NUMERIC(10,2) DEFAULT 0,
  free_shipping_threshold NUMERIC(10,2) DEFAULT 0,
  return_period INTEGER DEFAULT 7,
  order_prefix TEXT DEFAULT 'RJ',
  invoice_prefix TEXT DEFAULT 'INV',
  coupon_stacking_rule TEXT DEFAULT 'single',
  offer_stacking_rule TEXT DEFAULT 'single',
  low_stock_threshold INTEGER DEFAULT 3,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migration-safe additions for an existing site_settings table.
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS site_name TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS hero_badge TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS hero_title TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS hero_description TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS hero_image_url TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS primary_button_text TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS primary_button_link TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS secondary_button_text TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS secondary_button_link TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS announcement_text TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS announcement_subtext TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS whatsapp_number TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS instagram_url TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS facebook_url TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS footer_copyright TEXT;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'INR';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS shipping_fee NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS free_shipping_threshold NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS return_period INTEGER DEFAULT 7;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS order_prefix TEXT DEFAULT 'RJ';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS invoice_prefix TEXT DEFAULT 'INV';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS coupon_stacking_rule TEXT DEFAULT 'single';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS offer_stacking_rule TEXT DEFAULT 'single';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER DEFAULT 3;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_media_type ON public.media(media_type);
CREATE INDEX IF NOT EXISTS idx_banners_is_active ON public.banners(is_active);
CREATE INDEX IF NOT EXISTS idx_banners_display_order ON public.banners(display_order);
CREATE INDEX IF NOT EXISTS idx_banners_status ON public.banners(status);
CREATE INDEX IF NOT EXISTS idx_banners_start_at ON public.banners(start_at);
CREATE INDEX IF NOT EXISTS idx_banners_end_at ON public.banners(end_at);
CREATE INDEX IF NOT EXISTS idx_banners_status_display_order ON public.banners(status, display_order);
CREATE INDEX IF NOT EXISTS idx_banners_status_order ON public.banners(status, display_order);
CREATE INDEX IF NOT EXISTS idx_collections_status_order ON public.collections(status, display_order);
CREATE INDEX IF NOT EXISTS idx_collection_products_collection ON public.collection_products(collection_id, display_order);
CREATE INDEX IF NOT EXISTS idx_collection_products_product ON public.collection_products(product_id);

ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read media" ON public.media;
DROP POLICY IF EXISTS "Admin insert media" ON public.media;
DROP POLICY IF EXISTS "Admin update media" ON public.media;
DROP POLICY IF EXISTS "Admin delete media" ON public.media;
CREATE POLICY "Public read media" ON public.media FOR SELECT USING (true);
CREATE POLICY "Admin insert media" ON public.media FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admin update media" ON public.media FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admin delete media" ON public.media FOR DELETE TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "Public read active banners" ON public.banners;
DROP POLICY IF EXISTS "Admin full access banners" ON public.banners;
DROP POLICY IF EXISTS "Admin insert banners" ON public.banners;
DROP POLICY IF EXISTS "Admin update banners" ON public.banners;
DROP POLICY IF EXISTS "Admin delete banners" ON public.banners;
CREATE POLICY "Public read active banners" ON public.banners FOR SELECT USING (
  (
    (is_active = true OR is_active IS NULL)
    AND (status IN ('published', 'Active') OR status IS NULL)
    AND (start_at IS NULL OR start_at <= NOW())
    AND (end_at IS NULL OR end_at >= NOW())
  )
  OR public.is_admin()
);
CREATE POLICY "Admin insert banners" ON public.banners FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admin update banners" ON public.banners FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admin delete banners" ON public.banners FOR DELETE TO authenticated USING (public.is_admin());
GRANT SELECT ON public.banners TO anon, authenticated;
GRANT ALL ON public.banners TO authenticated, service_role;

DROP POLICY IF EXISTS "Public read active collections" ON public.collections;
DROP POLICY IF EXISTS "Admin insert collections" ON public.collections;
DROP POLICY IF EXISTS "Admin update collections" ON public.collections;
DROP POLICY IF EXISTS "Admin delete collections" ON public.collections;
CREATE POLICY "Public read active collections" ON public.collections FOR SELECT USING (status = 'Active' OR public.is_admin());
CREATE POLICY "Admin insert collections" ON public.collections FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admin update collections" ON public.collections FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admin delete collections" ON public.collections FOR DELETE TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "Public read active collection products" ON public.collection_products;
DROP POLICY IF EXISTS "Admin insert collection products" ON public.collection_products;
DROP POLICY IF EXISTS "Admin update collection products" ON public.collection_products;
DROP POLICY IF EXISTS "Admin delete collection products" ON public.collection_products;
CREATE POLICY "Public read active collection products" ON public.collection_products FOR SELECT USING (EXISTS (SELECT 1 FROM public.collections c WHERE c.id = collection_products.collection_id AND c.status = 'Active') OR public.is_admin());
CREATE POLICY "Admin insert collection products" ON public.collection_products FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admin update collection products" ON public.collection_products FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admin delete collection products" ON public.collection_products FOR DELETE TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "Public read site settings" ON public.site_settings;
DROP POLICY IF EXISTS "Admin insert site settings" ON public.site_settings;
DROP POLICY IF EXISTS "Admin update site settings" ON public.site_settings;
DROP POLICY IF EXISTS "Admin delete site settings" ON public.site_settings;
CREATE POLICY "Public read site settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Admin insert site settings" ON public.site_settings FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admin update site settings" ON public.site_settings FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admin delete site settings" ON public.site_settings FOR DELETE TO authenticated USING (public.is_admin());

INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public read media storage" ON storage.objects;
DROP POLICY IF EXISTS "Admin insert media storage" ON storage.objects;
DROP POLICY IF EXISTS "Admin update media storage" ON storage.objects;
DROP POLICY IF EXISTS "Admin delete media storage" ON storage.objects;
CREATE POLICY "Public read media storage" ON storage.objects FOR SELECT USING (bucket_id = 'media');
CREATE POLICY "Admin insert media storage" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'media' AND public.is_admin());
CREATE POLICY "Admin update media storage" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'media' AND public.is_admin()) WITH CHECK (bucket_id = 'media' AND public.is_admin());
CREATE POLICY "Admin delete media storage" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'media' AND public.is_admin());

DROP TRIGGER IF EXISTS set_media_updated_at ON public.media;
CREATE TRIGGER set_media_updated_at BEFORE UPDATE ON public.media FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
DROP TRIGGER IF EXISTS set_banners_updated_at ON public.banners;
CREATE TRIGGER set_banners_updated_at BEFORE UPDATE ON public.banners FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
DROP TRIGGER IF EXISTS set_collections_updated_at ON public.collections;
CREATE TRIGGER set_collections_updated_at BEFORE UPDATE ON public.collections FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================================
-- 17. ROYRA COMMERCE OPERATIONS: ORDERS / PAYMENTS / COUPONS / OFFERS /
--     INVENTORY / PURCHASE ORDERS / RETURNS / REFUNDS / SHIPPING / CUSTOMERS
-- ============================================================================

CREATE SEQUENCE IF NOT EXISTS public.royra_order_number_seq START 1;

CREATE TABLE IF NOT EXISTS public.customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT,
  shipping_address JSONB NOT NULL DEFAULT '{}'::jsonb,
  billing_address JSONB NOT NULL DEFAULT '{}'::jsonb,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  coupon_code TEXT,
  offer_discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  shipping_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'INR',
  payment_method TEXT NOT NULL DEFAULT 'COD',
  payment_status TEXT NOT NULL DEFAULT 'Pending' CHECK (payment_status IN ('Pending','Authorized','Paid','Failed','Refund Pending','Partially Refunded','Refunded')),
  order_status TEXT NOT NULL DEFAULT 'Pending Payment' CHECK (order_status IN ('Pending Payment','Paid','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Return Requested','Returned','Refund Pending','Refunded')),
  payment_reference TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  product_name TEXT NOT NULL,
  sku TEXT,
  selected_size TEXT,
  selected_metal TEXT,
  unit_price NUMERIC(12,2) NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  line_total NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  note TEXT,
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'manual',
  payment_method TEXT NOT NULL,
  transaction_id TEXT,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'INR',
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Authorized','Paid','Failed','Refund Pending','Partially Refunded','Refunded')),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.coupons (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  description TEXT,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage','fixed','free_shipping')),
  discount_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  minimum_order_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  maximum_discount NUMERIC(12,2),
  usage_limit INTEGER,
  per_customer_limit INTEGER,
  starts_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  applicable_category TEXT,
  applicable_product_ids BIGINT[],
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.coupon_usages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id UUID NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  offer_type TEXT NOT NULL CHECK (offer_type IN ('percentage','fixed','free_shipping')),
  discount_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  minimum_order_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  minimum_quantity INTEGER NOT NULL DEFAULT 1,
  applicable_category TEXT,
  applicable_product_ids BIGINT[],
  starts_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  priority INTEGER NOT NULL DEFAULT 100,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity_change INTEGER NOT NULL,
  movement_type TEXT NOT NULL,
  reason TEXT,
  reference_type TEXT,
  reference_id TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  address TEXT,
  gstin TEXT,
  payment_terms TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_number TEXT UNIQUE NOT NULL,
  supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Sent','Partially Received','Received','Cancelled')),
  expected_date DATE,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id BIGINT NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  received_quantity INTEGER NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  purchase_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  line_total NUMERIC(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'Requested' CHECK (status IN ('Requested','Approved','Rejected','Pickup Scheduled','Received','Refund Pending','Completed')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.refunds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  payment_id BIGINT REFERENCES public.payments(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'Requested' CHECK (status IN ('Requested','Processing','Completed','Failed')),
  refund_reference TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT UNIQUE NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  shipping_method TEXT DEFAULT 'Insured Express',
  courier TEXT,
  tracking_number TEXT,
  tracking_url TEXT,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending','Packed','Shipped','Out for Delivery','Delivered','Cancelled')),
  shipped_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(order_status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_order ON public.payments(order_id);
CREATE INDEX IF NOT EXISTS idx_coupon_code ON public.coupons(code);
CREATE INDEX IF NOT EXISTS idx_offers_active ON public.offers(active, priority);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product ON public.inventory_movements(product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_status ON public.purchase_orders(status);
CREATE INDEX IF NOT EXISTS idx_returns_status ON public.returns(status);
CREATE INDEX IF NOT EXISTS idx_refunds_status ON public.refunds(status);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;

-- Admin-only management for operational data. Checkout uses a SECURITY DEFINER RPC below.
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['customers','orders','order_items','order_status_history','payments','coupons','coupon_usages','offers','inventory_movements','suppliers','purchase_orders','purchase_order_items','returns','refunds','shipments'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Admin full access %s" ON public.%I', t, t);
    EXECUTE format('CREATE POLICY "Admin full access %s" ON public.%I FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())', t, t);
  END LOOP;
END $$;

-- Public may inspect active coupons through the secure validation RPC only; do not expose raw coupon rows.
-- Public may create orders only through public.place_order_secure().
CREATE OR REPLACE FUNCTION public.place_order_secure(
  p_customer JSONB,
  p_items JSONB,
  p_coupon_code TEXT DEFAULT NULL,
  p_payment_method TEXT DEFAULT 'COD'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_customer_id UUID;
  v_order_id BIGINT;
  v_order_number TEXT;
  v_subtotal NUMERIC(12,2) := 0;
  v_discount NUMERIC(12,2) := 0;
  v_offer_discount NUMERIC(12,2) := 0;
  v_shipping NUMERIC(12,2) := 0;
  v_tax NUMERIC(12,2) := 0;
  v_total NUMERIC(12,2) := 0;
  v_coupon coupons%ROWTYPE;
  v_offer offers%ROWTYPE;
  v_coupon_discount NUMERIC(12,2) := 0;
  v_eligible_subtotal NUMERIC(12,2) := 0;
  v_item JSONB;
  v_product products%ROWTYPE;
  v_qty INTEGER;
  v_line NUMERIC(12,2);
  v_now TIMESTAMPTZ := NOW();
BEGIN
  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Cart is empty';
  END IF;

  INSERT INTO public.customers(user_id, full_name, email, phone)
  VALUES (auth.uid(), COALESCE(p_customer->>'full_name','Guest Customer'), lower(trim(COALESCE(p_customer->>'email',''))), NULLIF(p_customer->>'phone',''))
  ON CONFLICT DO NOTHING;

  SELECT id INTO v_customer_id
  FROM public.customers
  WHERE lower(email)=lower(trim(COALESCE(p_customer->>'email','')))
  ORDER BY created_at ASC LIMIT 1;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_qty := GREATEST(1, LEAST(100, COALESCE((v_item->>'quantity')::INTEGER, 1)));
    SELECT * INTO v_product FROM public.products WHERE id = (v_item->>'product_id')::BIGINT AND status='Active' FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Product % is unavailable', v_item->>'product_id'; END IF;
    IF COALESCE(v_product.stock_quantity,0) < v_qty THEN RAISE EXCEPTION 'Insufficient stock for %', v_product.name; END IF;
    v_line := COALESCE(v_product.price, v_product.regular_price, 0) * v_qty;
    v_subtotal := v_subtotal + v_line;
  END LOOP;

  -- Highest-priority active automatic offer. One automatic offer is applied to prevent accidental stacking.
  SELECT * INTO v_offer
  FROM public.offers
  WHERE active=true
    AND (starts_at IS NULL OR starts_at <= v_now)
    AND (expires_at IS NULL OR expires_at >= v_now)
    AND v_subtotal >= minimum_order_value
  ORDER BY priority ASC, discount_value DESC
  LIMIT 1;

  IF v_offer.id IS NOT NULL THEN
    IF v_offer.offer_type='percentage' THEN v_offer_discount := ROUND(v_subtotal * v_offer.discount_value/100,2);
    ELSIF v_offer.offer_type='fixed' THEN v_offer_discount := LEAST(v_subtotal, v_offer.discount_value);
    END IF;
  END IF;

  IF p_coupon_code IS NOT NULL AND trim(p_coupon_code) <> '' THEN
    SELECT * INTO v_coupon FROM public.coupons WHERE upper(code)=upper(trim(p_coupon_code)) AND active=true LIMIT 1;
    IF NOT FOUND THEN RAISE EXCEPTION 'Invalid or inactive coupon code'; END IF;
    IF v_coupon.starts_at IS NOT NULL AND v_coupon.starts_at > v_now THEN RAISE EXCEPTION 'Coupon is not active yet'; END IF;
    IF v_coupon.expires_at IS NOT NULL AND v_coupon.expires_at < v_now THEN RAISE EXCEPTION 'Coupon has expired'; END IF;
    IF v_subtotal < v_coupon.minimum_order_value THEN RAISE EXCEPTION 'Minimum order value for coupon is ₹%', v_coupon.minimum_order_value;
    END IF;
    IF v_coupon.usage_limit IS NOT NULL AND (SELECT COUNT(*) FROM public.coupon_usages WHERE coupon_id=v_coupon.id) >= v_coupon.usage_limit THEN
      RAISE EXCEPTION 'Coupon usage limit reached';
    END IF;
    IF v_coupon.discount_type='percentage' THEN v_coupon_discount := ROUND((v_subtotal - LEAST(v_offer_discount,v_subtotal)) * v_coupon.discount_value/100,2);
    ELSIF v_coupon.discount_type='fixed' THEN v_coupon_discount := LEAST(v_subtotal - LEAST(v_offer_discount,v_subtotal), v_coupon.discount_value);
    ELSIF v_coupon.discount_type='free_shipping' THEN v_coupon_discount := 0; v_shipping := 0;
    END IF;
    IF v_coupon.maximum_discount IS NOT NULL THEN v_coupon_discount := LEAST(v_coupon_discount, v_coupon.maximum_discount); END IF;
  END IF;

  v_discount := LEAST(v_subtotal, v_offer_discount + v_coupon_discount);
  v_total := GREATEST(0, v_subtotal - v_discount + v_shipping + v_tax);

  v_order_number := 'RJ-' || TO_CHAR(v_now,'YYYYMMDD') || '-' || LPAD(nextval('public.royra_order_number_seq')::TEXT,6,'0');

  INSERT INTO public.orders(
    order_number, customer_id, customer_name, customer_email, customer_phone,
    shipping_address, billing_address, subtotal, discount_total, coupon_code,
    offer_discount, shipping_amount, tax_amount, total_amount, currency,
    payment_method, payment_status, order_status
  ) VALUES (
    v_order_number, v_customer_id,
    COALESCE(p_customer->>'full_name','Guest Customer'),
    lower(trim(COALESCE(p_customer->>'email',''))), NULLIF(p_customer->>'phone',''),
    COALESCE(p_customer->'shipping_address','{}'::jsonb),
    COALESCE(p_customer->'billing_address',COALESCE(p_customer->'shipping_address','{}'::jsonb)),
    v_subtotal, v_discount, NULLIF(upper(trim(p_coupon_code)) ,''),
    v_offer_discount, v_shipping, v_tax, v_total, 'INR',
    COALESCE(p_payment_method,'COD'), 'Pending', 'Pending Payment'
  ) RETURNING id INTO v_order_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_qty := GREATEST(1, LEAST(100, COALESCE((v_item->>'quantity')::INTEGER, 1)));
    SELECT * INTO v_product FROM public.products WHERE id = (v_item->>'product_id')::BIGINT FOR UPDATE;
    v_line := COALESCE(v_product.price, v_product.regular_price, 0) * v_qty;
    INSERT INTO public.order_items(order_id,product_id,product_name,sku,selected_size,selected_metal,unit_price,quantity,line_total)
    VALUES(v_order_id,v_product.id,v_product.name,v_product.sku,v_item->>'size',v_item->>'metal',COALESCE(v_product.price,v_product.regular_price,0),v_qty,v_line);
    UPDATE public.products SET stock_quantity=GREATEST(0,stock_quantity-v_qty), updated_at=NOW() WHERE id=v_product.id;
    INSERT INTO public.inventory_movements(product_id,quantity_change,movement_type,reason,reference_type,reference_id)
    VALUES(v_product.id,-v_qty,'SALE','Customer order','order',v_order_number);
  END LOOP;

  INSERT INTO public.order_status_history(order_id,status,note,changed_by) VALUES(v_order_id,'Pending Payment','Order created',auth.uid());
  INSERT INTO public.payments(order_id,payment_method,amount,status) VALUES(v_order_id,COALESCE(p_payment_method,'COD'),v_total,'Pending');
  INSERT INTO public.shipments(order_id,status) VALUES(v_order_id,'Pending');

  IF v_coupon.id IS NOT NULL THEN
    INSERT INTO public.coupon_usages(coupon_id,order_id,customer_id,discount_amount) VALUES(v_coupon.id,v_order_id,v_customer_id,v_coupon_discount);
  END IF;

  RETURN jsonb_build_object('success',true,'order_id',v_order_id,'order_number',v_order_number,'subtotal',v_subtotal,'discount',v_discount,'total',v_total,'payment_status','Pending');
END;
$$;

GRANT EXECUTE ON FUNCTION public.place_order_secure(JSONB,JSONB,TEXT,TEXT) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.validate_coupon_secure(p_code TEXT, p_subtotal NUMERIC)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE c coupons%ROWTYPE; v_discount NUMERIC(12,2) := 0; v_now TIMESTAMPTZ := NOW();
BEGIN
  SELECT * INTO c FROM public.coupons WHERE UPPER(code)=UPPER(TRIM(p_code)) AND active=true LIMIT 1;
  IF NOT FOUND THEN RETURN jsonb_build_object('valid',false,'error','Invalid or inactive coupon'); END IF;
  IF c.starts_at IS NOT NULL AND c.starts_at>v_now THEN RETURN jsonb_build_object('valid',false,'error','Coupon is not active yet'); END IF;
  IF c.expires_at IS NOT NULL AND c.expires_at<v_now THEN RETURN jsonb_build_object('valid',false,'error','Coupon has expired'); END IF;
  IF p_subtotal < c.minimum_order_value THEN RETURN jsonb_build_object('valid',false,'error',format('Minimum order value is ₹%s',c.minimum_order_value)); END IF;
  IF c.usage_limit IS NOT NULL AND (SELECT COUNT(*) FROM public.coupon_usages WHERE coupon_id=c.id)>=c.usage_limit THEN RETURN jsonb_build_object('valid',false,'error','Coupon usage limit reached'); END IF;
  IF c.discount_type='percentage' THEN v_discount:=ROUND(p_subtotal*c.discount_value/100,2); ELSIF c.discount_type='fixed' THEN v_discount:=LEAST(p_subtotal,c.discount_value); ELSE v_discount:=0; END IF;
  IF c.maximum_discount IS NOT NULL THEN v_discount:=LEAST(v_discount,c.maximum_discount); END IF;
  RETURN jsonb_build_object('valid',true,'discount',v_discount,'code',c.code,'discount_type',c.discount_type);
END; $$;
GRANT EXECUTE ON FUNCTION public.validate_coupon_secure(TEXT,NUMERIC) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.update_order_status_secure(p_order_id BIGINT, p_status TEXT, p_note TEXT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;
  UPDATE public.orders SET order_status=p_status, updated_at=NOW() WHERE id=p_order_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Order not found'; END IF;
  INSERT INTO public.order_status_history(order_id,status,note,changed_by) VALUES(p_order_id,p_status,p_note,auth.uid());
  RETURN jsonb_build_object('success',true);
END; $$;
GRANT EXECUTE ON FUNCTION public.update_order_status_secure(BIGINT,TEXT,TEXT) TO authenticated;
