(function(){
'use strict';
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function toast(m,t='success'){window.showAdminToast?window.showAdminToast(m,t):alert(m)}
window.escAdmin=esc;
window.initOrdersPage=async function(){
 const tbody=document.querySelector('#orders-tbody'), search=document.querySelector('#orders-search'), status=document.querySelector('#orders-status'), pay=document.querySelector('#orders-payment');
 async function load(){const rows=await RoyraDB.getOrders({search:search?.value||'',status:status?.value||'all',paymentStatus:pay?.value||'all'}); tbody.innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${esc(o.order_number)}</strong><br><small>${new Date(o.created_at).toLocaleString('en-IN')}</small></td><td>${esc(o.customer_name)}<br><small>${esc(o.customer_email)}</small></td><td>${formatINR(o.total_amount)}</td><td><span class="status-badge ${o.payment_status.toLowerCase().replace(/\s+/g,'-')}">${esc(o.payment_status)}</span></td><td><select data-order="${o.id}" class="ops-inline-status">${['Pending Payment','Paid','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Return Requested','Returned','Refund Pending','Refunded'].map(s=>`<option ${s===o.order_status?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="btn-action" onclick="viewOrder(${o.id})">View</button><button class="btn-action edit" onclick="markPaid(${o.id})">Mark Paid</button></td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center;color:#777">No orders found.</td></tr>'; document.querySelectorAll('.ops-inline-status').forEach(el=>el.onchange=async()=>{const r=await RoyraDB.updateOrderStatus(el.dataset.order,el.value,'Updated from Admin Panel');toast(r.success?'Order updated':r.error,r.success?'success':'error');});}
 search?.addEventListener('input',load);status?.addEventListener('change',load);pay?.addEventListener('change',load);window.reloadOrders=load;await load();
};
window.viewOrder=async function(id){const o=await RoyraDB.getOrder(id);if(!o){toast('Order could not be loaded','error');return}const items=(o.order_items||[]).map(i=>`<tr><td>${esc(i.product_name)}<br><small>${esc(i.sku||'')}</small></td><td>${i.quantity}</td><td>${formatINR(i.unit_price)}</td><td>${formatINR(i.line_total)}</td></tr>`).join('');const html=`<div class="ops-modal open"><div class="ops-modal-card"><button class="ops-close" onclick="this.closest('.ops-modal').remove()">✕</button><h2>${esc(o.order_number)}</h2><p>${esc(o.customer_name)} • ${esc(o.customer_email)}</p><div class="ops-grid"><div><b>Total</b><div>${formatINR(o.total_amount)}</div></div><div><b>Payment</b><div>${esc(o.payment_status)}</div></div><div><b>Status</b><div>${esc(o.order_status)}</div></div><div><b>Method</b><div>${esc(o.payment_method)}</div></div></div><h3>Items</h3><table class="admin-table"><thead><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>${items}</tbody></table><h3>Shipping Address</h3><pre class="ops-pre">${esc(JSON.stringify(o.shipping_address||{},null,2))}</pre><h3>Status History</h3><div>${(o.order_status_history||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(h=>`<div class="ops-history"><b>${esc(h.status)}</b><span>${new Date(h.created_at).toLocaleString('en-IN')}</span><small>${esc(h.note||'')}</small></div>`).join('')}</div></div></div>`;document.body.insertAdjacentHTML('beforeend',html)};
window.markPaid=async function(id){const r=await RoyraDB.updatePaymentStatus(id,'Paid');toast(r.success?'Payment marked Paid':r.error,r.success?'success':'error'); if(r.success&&window.reloadOrders)window.reloadOrders();};
window.initCouponsPage=async function(){const tbody=document.querySelector('#coupons-tbody');const form=document.querySelector('#coupon-form');const load=async()=>{const rows=await RoyraDB.getCoupons();tbody.innerHTML=rows.length?rows.map(c=>`<tr><td><strong>${esc(c.code)}</strong></td><td>${esc(c.discount_type)}</td><td>${c.discount_type==='percentage'?c.discount_value+'%':c.discount_type==='fixed'?formatINR(c.discount_value):'Free Shipping'}</td><td>${c.minimum_order_value?formatINR(c.minimum_order_value):'—'}</td><td>${c.active?'Active':'Inactive'}</td><td><button class="btn-action" onclick='editCoupon(${JSON.stringify(c)})'>Edit</button><button class="btn-action" onclick='deleteCoupon(${JSON.stringify(c.id)})'>Delete</button></td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center;color:#777">No coupons yet.</td></tr>'};window.reloadCoupons=load;await load();form?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const row=Object.fromEntries(fd.entries());row.discount_value=Number(row.discount_value||0);row.minimum_order_value=Number(row.minimum_order_value||0);row.maximum_discount=row.maximum_discount?Number(row.maximum_discount):null;row.usage_limit=row.usage_limit?Number(row.usage_limit):null;row.per_customer_limit=row.per_customer_limit?Number(row.per_customer_limit):null;row.active=fd.get('active')==='on';const r=await RoyraDB.saveCoupon(row);toast(r.success?'Coupon saved':r.error,r.success?'success':'error');if(r.success){form.reset();load();}})};
window.editCoupon=function(c){const f=document.querySelector('#coupon-form');for(const k of ['id','code','description','discount_type','discount_value','minimum_order_value','maximum_discount','usage_limit','per_customer_limit','starts_at','expires_at','applicable_category']){const el=f?.elements.namedItem(k);if(el)el.value=c[k]||'';}if(f?.elements.namedItem('active'))f.elements.namedItem('active').checked=!!c.active;scrollTo({top:0,behavior:'smooth'})};
window.deleteCoupon=async function(id){if(!confirm('Delete coupon?'))return;const r=await RoyraDB.deleteCoupon(id);toast(r.success?'Coupon deleted':r.error,r.success?'success':'error');if(r.success&&window.reloadCoupons)window.reloadCoupons();};
window.initOffersPage=async function(){const tbody=document.querySelector('#offers-tbody'),form=document.querySelector('#offer-form');const load=async()=>{const rows=await RoyraDB.getOffers();tbody.innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${esc(o.name)}</strong><br><small>${esc(o.description||'')}</small></td><td>${esc(o.offer_type)}</td><td>${o.offer_type==='percentage'?o.discount_value+'%':o.offer_type==='fixed'?formatINR(o.discount_value):'Free Shipping'}</td><td>${o.priority}</td><td>${o.active?'Active':'Inactive'}</td><td><button class="btn-action" onclick='editOffer(${JSON.stringify(o)})'>Edit</button><button class="btn-action" onclick='deleteOffer(${o.id})'>Delete</button></td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center;color:#777">No offers yet.</td></tr>'};window.reloadOffers=load;await load();form?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const row=Object.fromEntries(fd.entries());['discount_value','minimum_order_value','minimum_quantity','priority'].forEach(k=>row[k]=Number(row[k]||0));row.active=fd.get('active')==='on';const r=await RoyraDB.saveOffer(row);toast(r.success?'Offer saved':r.error,r.success?'success':'error');if(r.success){form.reset();load();}})};
window.editOffer=function(o){const f=document.querySelector('#offer-form');for(const k of ['id','name','description','offer_type','discount_value','minimum_order_value','minimum_quantity','applicable_category','priority','starts_at','expires_at']){const el=f?.elements.namedItem(k);if(el)el.value=o[k]||'';}if(f?.elements.namedItem('active'))f.elements.namedItem('active').checked=!!o.active;scrollTo({top:0,behavior:'smooth'})};window.deleteOffer=async id=>{if(!confirm('Delete offer?'))return;const r=await RoyraDB.deleteOffer(id);toast(r.success?'Offer deleted':r.error,r.success?'success':'error');if(r.success&&window.reloadOffers)window.reloadOffers();};
window.initInventoryPage=async function(){const tbody=document.querySelector('#inventory-tbody'),search=document.querySelector('#inventory-search');async function load(){let rows=await RoyraDB.getInventory();if(search?.value)rows=rows.filter(x=>`${x.name} ${x.sku}`.toLowerCase().includes(search.value.toLowerCase()));tbody.innerHTML=rows.map(p=>`<tr><td>${esc(p.name)}<br><small>${esc(p.sku)}</small></td><td>${esc(p.category)}</td><td><strong>${p.stock_quantity}</strong></td><td>${p.low_stock_alert}</td><td><span class="status-badge ${p.stock_quantity<=0?'out-of-stock':p.stock_quantity<=p.low_stock_alert?'pending':'active'}">${p.stock_quantity<=0?'Out of Stock':p.stock_quantity<=p.low_stock_alert?'Low Stock':'In Stock'}</span></td><td><button class="btn-action" onclick="adjustInventory(${p.id},1)">+1</button><button class="btn-action" onclick="adjustInventory(${p.id},-1)">-1</button></td></tr>`).join('')};window.reloadInventory=load;search?.addEventListener('input',load);await load();};window.adjustInventory=async(id,delta)=>{const reason=prompt('Reason for stock adjustment?')||'Manual adjustment';const r=await RoyraDB.adjustStock(id,delta,reason);toast(r.success?`Stock updated: ${r.stock}`:r.error,r.success?'success':'error');if(r.success&&window.reloadInventory)window.reloadInventory();};
window.initPaymentsPage=async()=>{const tb=document.querySelector('#payments-tbody');const rows=await RoyraDB.getPayments();tb.innerHTML=rows.length?rows.map(p=>`<tr><td>${p.orders?.order_number||'—'}</td><td>${p.orders?.customer_name||'—'}</td><td>${formatINR(p.amount)}</td><td>${esc(p.payment_method)}</td><td>${esc(p.status)}</td><td>${p.transaction_id||'—'}</td><td>${new Date(p.created_at).toLocaleString('en-IN')}</td></tr>`).join(''):'<tr><td colspan="7" style="padding:40px;text-align:center">No payment records.</td></tr>';};
window.initReturnsPage=async()=>{const tb=document.querySelector('#returns-tbody');const rows=await RoyraDB.getReturns();tb.innerHTML=rows.length?rows.map(r=>`<tr><td>#${r.id}</td><td>${r.orders?.order_number||'—'}</td><td>${r.orders?.customer_name||'—'}</td><td>${esc(r.reason||'')}</td><td>${esc(r.status)}</td><td>${new Date(r.created_at).toLocaleString('en-IN')}</td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center">No returns.</td></tr>';};
window.initRefundsPage=async()=>{const tb=document.querySelector('#refunds-tbody');const rows=await RoyraDB.getRefunds();tb.innerHTML=rows.length?rows.map(r=>`<tr><td>#${r.id}</td><td>${r.orders?.order_number||'—'}</td><td>${r.orders?.customer_name||'—'}</td><td>${formatINR(r.amount)}</td><td>${esc(r.status)}</td><td>${esc(r.reason||'')}</td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center">No refunds.</td></tr>';};
window.initShippingPage=async()=>{const tb=document.querySelector('#shipping-tbody');const rows=await RoyraDB.getShipments();tb.innerHTML=rows.length?rows.map(s=>`<tr><td>${s.orders?.order_number||'—'}</td><td>${s.orders?.customer_name||'—'}</td><td>${esc(s.shipping_method||'')}</td><td>${esc(s.courier||'—')}</td><td>${esc(s.tracking_number||'—')}</td><td>${esc(s.status||'Pending')}</td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center">No shipments.</td></tr>';};
window.initCustomersPage=async()=>{const tb=document.querySelector('#customers-tbody');const rows=await RoyraDB.getCustomersFromOrders();tb.innerHTML=rows.length?rows.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.email)}</td><td>${esc(c.phone||'—')}</td><td>${c.orders}</td><td>${formatINR(c.total_spent)}</td><td>${new Date(c.last_order).toLocaleDateString('en-IN')}</td></tr>`).join(''):'<tr><td colspan="6" style="padding:40px;text-align:center">No customers with orders yet.</td></tr>';};
})();
